version: '3'

services:
  # Laravel App 1
  laravel_app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    volumes:
      - ./app1:/var/www/html
    networks:
      - laravel_network

  # Laravel App 2
  laravel_app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    volumes:
      - ./app2:/var/www/html
    networks:
      - laravel_network

  # Nginx for Laravel App 1
  nginx_app1:
    image: nginx:1.25.4-alpine
    ports:
      - "8001:80"
    volumes:
      - ./app1:/var/www/html
      - ./nginx_conf/app1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - laravel_app1

  # Nginx for Laravel App 2
  nginx_app2:
    image: nginx:1.25.4-alpine
    ports:
      - "8002:80"
    volumes:
      - ./app2:/var/www/html
      - ./nginx_conf/app2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - laravel_app2

  # PHP-FPM for Laravel App 1
  php_fpm_app1:
    image: php:8.2.16-fpm-alpine
    volumes:
      - ./app1:/var/www/html
    networks:
      - laravel_network

  # PHP-FPM for Laravel App 2
  php_fpm_app2:
    image: php:8.2.16-fpm-alpine
    volumes:
      - ./app2:/var/www/html
    networks:
      - laravel_network

  # MySQL
  mysql:
    image: mysql:8.2.0
    restart: always
    volumes:
      - ./mysql-volumes:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 12345678
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    networks:
      - laravel_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 12345678
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 500M
      PMA_CONTROLUSER: root
      PMA_CONTROLPASS: 12345678
      SERVICE_NAME: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - mysql

networks:
  laravel_network:
    driver: bridge
